config/routes.rb
Rails.application.routes.draw do

  resources :user_stocks
  devise_for :users
  root 'users#my_portfolio'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'

  resources :users, only: [:index, :show]
  resources :stocks, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
      endpoint: 'https://sandbox.iexapis.com/v1'
    )
    begin
      new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
    rescue => e
      nil
    end
  end

  validates :name, :ticker, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def index
    @stocks = Stock.order(params[:sort])
  end
  
  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock].upcase)
      if @stock
        respond_to do |format|
          format.js { render partial: "users/result" }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a valid symbol"
          format.js { render partial: "users/result" }
        end
      end
=begin      
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a symbol"
        format.js { render partial: "users/result" }
      end
=end
    end
  end

  private

  def stock_params
    params.require(:stock).permit(:ticker, :name, :last_price)
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock = Stock.find_by(ticker: params[:stock][:ticker])

    stock ? stock.save : stock = Stock.new(name: params[:stock][:name], ticker: params[:stock][:ticker].upcase)

    user_stock = UserStock.new(stock: stock, user: current_user)

    redirect_back(fallback_location: root_path)

    flash[:notice] = 'Stock saved!' if user_stock.save
  end

  def destroy
    userstock = UserStock.find_by(stock_id: params[:id], user_id: params[:user_id])

    redirect_back(fallback_location: root_path)

    flash[:alert] = 'Stock removed!' if userstock.destroy
  end

  def update
    stock = Stock.find(params[:id])

    user_stock = UserStock.new(stock: stock, user: current_user)

    redirect_back(fallback_location: root_path)

    flash[:notice] = 'Stock saved!' if user_stock.save
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end

  def my_portfolio
    @tracked_stocks = current_user.stocks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
		<%= notice %>
	</div>
<% end %>
<% if alert %>
	<div class='alert alert-danger'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
		<%= alert %>
	</div>
<% end %> 

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light border-bottom border-bg-dark shadow-sm p-1 mb-5 bg-white rounded">
  <div class="container">
    <%= link_to image_tag("stock_market.jpg", style: "width:100px;height:auto;"), root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Portfolio", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Search stock", search_stock_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Trending stocks", stocks_path, class: "nav-link" %>
        </li>        
      </ul>
      <% if user_signed_in? %>
      <ul class="navbar-nav">
          <li class="nav-item">
           <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: "nav-link" %>
          </li>
        </ul>
      <% end %>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stocktracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @tracked_stocks.each do |stock| %>
          <tr>
            <th scope="row"><%= stock.ticker %></th>
            <td><%= stock.name %></td>
            <td>$<%= Stock.new_lookup(stock.ticker).last_price %></td>
            <% if params[:id] %>

              <% if current_user.stocks.exists?(ticker: stock.ticker) %>
                <td>
                  <%= button_to "Remove", {:controller => :user_stocks, :action => 'destroy', :id => Stock.find_by(ticker: stock.ticker).id }, :method => :delete, params: { user_id: current_user.id }, class: "btn btn-danger w-100" %>
                </td>
              <% else %>
                <td>
                  <%= form_for stock, :url => {:action => "update", :id => stock, :controller => "user_stocks"} do |f| %>
                    <%= f.hidden_field :ticker, value: stock.ticker %>
                    <%= f.hidden_field :name, value: stock.name %>
                    <%= f.hidden_field :last_price, value: stock.last_price %>
                    <%= button_tag type: :submit, class: "btn btn-success w-100" do %>
                      Add
                    <% end %>
                  <% end %>
                </td>
              <% end %>
            <% else %>
              <td>
                <%= button_to "Remove", {:controller => :user_stocks, :action => 'destroy', :id => stock.id }, :method => :delete, params: { user_id: current_user.id }, class: "btn btn-danger w-100" %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/stocks/index.html.erb
<div class="row">
  <div class="col-9">
    <table class="sortable table table-bordered table-hover">
      <thead>
        <tr>
          <th><%= link_to "Ticker", :sort => "ticker"%> </th>
          <th><%= link_to "Name", :sort => "name"%> </th>
          <th scope="col">Price</th>
          <th scope="col">Followed by</th>
          <th scope="col">Add / remove</th>
        </tr>
      </thead>
      <tbody>
        <% @stocks.each do |stock| %>
          <% unless stock.users.empty? %>
            <tr>
              <th scope="row"><%= stock.ticker %></th>
              <td><%= stock.name %></td>
              <td>$<%= Stock.new_lookup(stock.ticker).last_price %></td>
              <td><%= pluralize(stock.users.count, 'user') %></td>

              <td>
                <% if current_user.stocks.exists?(ticker: stock.ticker) %>
                  <%= button_to "Remove", {:controller => :user_stocks, :action => 'destroy', :id => Stock.find_by(ticker: stock.ticker).id }, :method => :delete, params: { user_id: current_user.id }, class: "btn btn-danger w-100" %>
                <% else %>
                  <%= form_for stock, :url => {:action => "update", :id => stock, :controller => "user_stocks"} do |f| %>
                    <%= f.hidden_field :ticker, value: stock.ticker %>
                    <%= f.hidden_field :name, value: stock.name %>
                    <%= f.hidden_field :last_price, value: stock.last_price %>
                    <%= button_tag type: :submit, class: "btn btn-success w-100" do %>
                      Add
                    <% end %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/stocks/search.html.erb
<h1>Stock search</h1>
<div class="search-area">
  <h3>Search stocks</h3>
  <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Enter stock ticker symbol", autofocus: true, class:"form-control form-control-lg" %>
      </div>
      <div class="col-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-primary" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="results">
  
</div>

app/views/users/_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @stock %>
  <div class="card card-header results-block">
    <div class="info mb-2">
      <strong>Symbol: </strong> <%= @stock.ticker %>
      <strong>Name: </strong> <%= @stock.name %>
      <strong>Last price: </strong> $<%= @stock.last_price %>
    </div>
    <% if current_user.stocks.exists?(ticker: @stock.ticker) %>
      <%= button_to "Remove", {:controller => :user_stocks, :action => 'destroy', :id => Stock.find_by(ticker: @stock.ticker).id }, :method => :delete, params: { user_id: current_user.id }, class: "btn btn-danger w-100" %>
    <% else %>
      <%= form_for @stock, :url => url_for(:controller => 'user_stocks', :action => 'create') do |f| %>
        <%= f.hidden_field :ticker, value: @stock.ticker %>
        <%= f.hidden_field :name, value: @stock.name %>
        <%= f.hidden_field :last_price, value: @stock.last_price %>
        <%= button_tag type: :submit, class: "btn btn-success w-100" do %>
          Add
        <% end %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'users/result.html' %>'

app/views/users/index.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">User</th>
          <th scope="col"># Stocks followed</th>
          <th scope="col">Portfolio detail</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <% unless user == current_user %>
            <tr>
              <td><%= user.email.split('@').first %></td>
              <td><%= pluralize(user.stocks.count, "stock") %></td>
              <td><%= link_to "Profile", user_path(user)  %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/my_portfolio.html.erb
<h1>My portfolio</h1>

<% unless @tracked_stocks.empty? %>
  <%= render 'stocks/list' %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.email.split('@').first.capitalize %>'s portfolio</h1>

<% unless @tracked_stocks.empty? %>
  <%= render 'stocks/list' %>
<% end %>

<%= link_to "Back to users", users_path %>

app/views/welcome/index.html.erb
<h1>Root page</h1>

<%= link_to "Sign out", destroy_user_session_path, method: :delete %>